name: Portfolio Deployment to VMware

on:
  push:
    branches:
      - main  # Jab bhi main branch par push ho

jobs:
  build-and-deploy:
    runs-on: self-hosted  # <--- Yeh aapke VMware runner ko bol raha hai kaam karne ko
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy static site to Local Nginx
      run: |
        # Purani default files ko saaf karein
        rm -rf /var/www/html/*
        
        # Naya portfolio ka code Nginx ke public folder mein copy karein
        cp -r . /var/www/html/
