name: Portfolio Deployment to VMware

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy static site to Local Nginx
      run: |
        # Purani files ko forcefully saaf karein agar hain toh
        rm -rf /var/www/html/*
        
        # Sirf website ka code copy karein, .git hidden folder ko chhor dein
        rsync -av --exclude='.git' ./ /var/www/html/
